# Generated by Django 6.0.6 on 2026-07-04 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "hole_cards",
                    models.JSONField(
                        help_text="Player hole cards as list of card strings"
                    ),
                ),
                (
                    "board",
                    models.JSONField(
                        default=list,
                        help_text="Community cards as list of card strings",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=list, help_text="Chronological list of action dicts"
                    ),
                ),
                (
                    "pot_size",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "preflop_chart_deviation",
                    models.FloatField(
                        blank=True,
                        help_text="EV loss from preflop GTO deviation",
                        null=True,
                    ),
                ),
                (
                    "postflop_ev_loss_by_street",
                    models.JSONField(
                        default=dict, help_text="EV loss breakdown by street"
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("win", "Win"), ("loss", "Loss"), ("tie", "Tie")],
                        default="loss",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
