# Generated by Django 6.0.6 on 2026-07-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker_engine", "0003_livehand"),
    ]

    operations = [
        migrations.AddField(
            model_name="handhistory",
            name="bot_profile",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Bot profile the hand was played against (balanced/nit/station/maniac)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="handhistory",
            name="net_bb",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hero net result in big blinds (positive = won chips)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
