# Generated by Django 6.0.6 on 2026-07-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkillObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill",
                    models.CharField(
                        choices=[
                            ("preflop_range", "Preflop Range"),
                            ("equity_estimation", "Equity Estimation"),
                            ("pot_odds", "Pot Odds"),
                            ("implied_odds", "Implied Odds"),
                            ("mdf", "Minimum Defense Frequency"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("correct", models.BooleanField()),
                (
                    "posterior_after",
                    models.FloatField(
                        help_text="BKT posterior mastery estimate after this observation"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("quiz", "Quiz"), ("hand", "Live Hand")], max_length=10
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
