# Generated by Django 6.0.6 on 2026-07-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_model", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillobservation",
            name="reference_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source scenario id (quiz) or hand id that produced this observation",
                max_length=50,
            ),
        ),
    ]
