# Generated by Django 6.0.6 on 2026-07-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_model", "0003_skillobservation_reference_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillobservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("infinite", "Generated Quiz"),
                    ("hand", "Live Hand"),
                ],
                max_length=10,
            ),
        ),
    ]
