# Generated by Django 6.0.6 on 2026-07-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_model", "0004_alter_skillobservation_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillobservation",
            name="skill",
            field=models.CharField(
                choices=[
                    ("preflop_range", "Preflop Range"),
                    ("equity_estimation", "Equity Estimation"),
                    ("pot_odds", "Pot Odds"),
                    ("implied_odds", "Implied Odds"),
                    ("mdf", "Minimum Defense Frequency"),
                    ("opponent_reading", "Opponent Reading"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="skillobservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("quiz", "Quiz"),
                    ("infinite", "Generated Quiz"),
                    ("hand", "Live Hand"),
                    ("exploit", "Exploit Lab"),
                ],
                max_length=10,
            ),
        ),
    ]
